### ISSUE TITLE
Figure out which ORM to use and answer questions

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-sql-plugin#1]
- How would the configuration work, specifically, does the user have to give mysql_connection_uri? or just connection_uri etc..?
- How can we force sqlite (in memory) db even if the user has given credentials for MySQL etc..
- If someone is only using MySQL, will this also give them PostgreSQL etc driver JARs?
- How can we wait for the db to start like we do now?
- Error handling differences across MySQL and postgres etc?
- How do differences in db get handled? For example postgres has a scheme config when connecting to it, but MySQL doesn't?
- Which license is the tool?
   - MySQL driver is a commercial one, so we use maria db instead - will that work?
- Specifying how transactions are done
- Specifying how FOR UPDATE queries are done
- How will db migratation work?

**Comment by siddharthmudgal** [comment]
### Draft One
- How would the configuration work, specifically, does the user have to give mysql_connection_uri? or just connection_uri etc..?
_Just connection_url_
- How can we force sqlite (in memory) db even if the user has given credentials for MySQL etc..
_Programatically possible_
- If someone is only using MySQL, will this also give them PostgreSQL etc driver JARs?
_No, this depends on our gradle configuration. We can approach this via environment variables or profiles_
- How can we wait for the db to start like we do now?
Should be doable via similar implementation
- Error handling differences across MySQL and postgres etc?
- How do differences in db get handled? For example postgres has a scheme config when connecting to it, but MySQL doesn't?
- Which license is the tool?
- MySQL driver is a commercial one, so we use maria db instead - will that work?
- Specifying how transactions are done
- Specifying how FOR UPDATE queries are done
- How will db migratation work?

**Comment by rishabhpoddar** [comment]
## Db migration scenarios
- Offline migration:
   - What happens if migration fails in the middle?
   - Specifying scripts for custom migration rules (like copying data from one table into another). What about bulk copying?
   - Going from a very old version to the latest version -> applying multiple migrations in one shot - how will that work?
- Online migration (We don't need to support this, but here is a list anyway)
   - Items in the offline migration list +
   - Different versions of the core running at the same time -> all data mutation must be backward compatible
   - Requirement to copy data from one table into another while the source table is being modified in real time

**Comment by siddharthmudgal** [comment]
ORM and DB migration management are two different things, therefore we will target migration under another ticket : 

Offline migration:
What happens if migration fails in the middle?
Specifying scripts for custom migration rules (like copying data from one table into another). What about bulk copying?
Going from a very old version to the latest version -> applying multiple migrations in one shot - how will that work?
Online migration (We don't need to support this, but here is a list anyway)
Items in the offline migration list +
Different versions of the core running at the same time -> all data mutation must be backward compatible
Requirement to copy data from one table into another while the source table is being modified in real time

**Comment by rishabhpoddar** [comment]
## More questions:
- Should we create a fat JAR or not? (do support all kinds of dbs)

**Comment by rishabhpoddar** [comment]
Closing this issue since we have answers to all the questions needed.
